/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/engines.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/engines.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Body_7.geometry} material={materials['DesignerPartSelected(Clone) (Instance)']} />
        <mesh geometry={nodes.Body_7_1.geometry} material={materials['DesignerSubPartSelected(Clone) (Instance)']} />
      </group>
      <mesh geometry={nodes.Engine1.geometry} material={materials['DesignerPartDisconnected(Clone) (Instance)']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Engine3.geometry} material={materials['DesignerPartDisconnected(Clone) (Instance)']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/engines.glb')
